In [2]:
import pandas as pd

In [4]:
cereals=pd.read_csv("cereals.csv")
cereals.head()

                        Name    Manufacturer  Type  Calories  Fiber  Sugars
0                  100% Bran         Nabisco  Cold        70   10.0       6
1          100% Natural Bran     Quaker Oats  Cold       120    2.0       8
2                   All-Bran       Kellogg's  Cold        70    9.0       5
3  All-Bran with Extra Fiber       Kellogg's  Cold        50   14.0       0
4             Almond Delight  Ralston Purina  Cold       110    1.0       8

In [6]:
#Manufacturer열의 값을 사용하여 시리얼을 그룹화하세요.
cereal_group=cereals.groupby("Manufacturer")
cereal_group

In [26]:
#그룹의 총 개수와 그룹별 시리얼의 개수를 구하시오
print("그룹의 총 개수: ",len(cereal_group))
cereal_group.size()

그룹의 총 개수:  7

Manufacturer
American Home Food Products     1
General Mills                  22
Kellogg's                      23
Nabisco                         6
Post                            9
Quaker Oats                     8
Ralston Purina                  8
dtype: int64

In [12]:
#제조업체 Nabisco에 속하는 시리얼을 추출하세요
cereal_group.get_group("Nabisco")

                         Name Manufacturer  Type  Calories  Fiber  Sugars
0                   100% Bran      Nabisco  Cold        70   10.0       6
20     Cream of Wheat (Quick)      Nabisco   Hot       100    1.0       0
63             Shredded Wheat      Nabisco  Cold        80    3.0       0
64     Shredded Wheat 'n'Bran      Nabisco  Cold        90    4.0       0
65  Shredded Wheat spoon size      Nabisco  Cold        90    3.0       0
68    Strawberry Fruit Wheats      Nabisco  Cold        90    3.0       5

In [13]:
#각 제조업체의 Calories, Fiber와 Sugars열 값의 평균을 계산하세요.
cereal_group.mean(numeric_only=True)

                               Calories     Fiber    Sugars
Manufacturer
American Home Food Products  100.000000  0.000000  3.000000
General Mills                111.363636  1.272727  7.954545
Kellogg's                    108.695652  2.739130  7.565217
Nabisco                       86.666667  4.000000  1.833333
Post                         108.888889  2.777778  8.777778
Quaker Oats                   95.000000  1.337500  5.250000
Ralston Purina               115.000000  1.875000  6.125000

In [14]:
#각 제조업체의 Sugars열에서 최댓값을 찾으세요.
cereal_group["Sugars"].max()

Manufacturer
American Home Food Products     3
General Mills                  14
Kellogg's                      15
Nabisco                         6
Post                           15
Quaker Oats                    12
Ralston Purina                 11
Name: Sugars, dtype: int64

In [15]:
#각 제조업체의 Fiber열에서 최솟값을 찾으세요.
cereal_group["Fiber"].min()

Manufacturer
American Home Food Products    0.0
General Mills                  0.0
Kellogg's                      0.0
Nabisco                        1.0
Post                           0.0
Quaker Oats                    0.0
Ralston Purina                 0.0
Name: Fiber, dtype: float64

제조업체별로 설탕 함량이 가장 낮은 시리얼을 새로운 DataFrame으로 추출하세요.

In [23]:
def smallest_sugar(df):
    return df.nsmallest(n=1,columns="Sugars")

In [25]:
cereal_group.apply(smallest_sugar)

/var/folders/g2/m_rjbg_d4fq330k9g6z2v24m0000gn/T/ipykernel_1283/3560163230.py:1: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  cereal_group.apply(smallest_sugar)

,,Name,Manufacturer,Type,Calories,Fiber,Sugars
Manufacturer,,,,,,,
American Home Food Products,43,Maypo,American Home Food Products,Hot,100,0.0,3
General Mills,11,Cheerios,General Mills,Cold,110,2.0,1
Kellogg's,3,All-Bran with Extra Fiber,Kellogg's,Cold,50,14.0,0
Nabisco,20,Cream of Wheat (Quick),Nabisco,Hot,100,1.0,0
Post,33,Grape-Nuts,Post,Cold,110,3.0,3
Quaker Oats,57,Quaker Oatmeal,Quaker Oats,Hot,100,2.7,-1
Ralston Purina,61,Rice Chex,Ralston Purina,Cold,110,0.0,2