In [1]:
import pandas as pd

In [22]:
#dataset 최적화
netflix=pd.read_csv("netflix.csv",
                    parse_dates=["date_added"])
netflix

/var/folders/g2/m_rjbg_d4fq330k9g6z2v24m0000gn/T/ipykernel_1882/3068006855.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  netflix=pd.read_csv("netflix.csv",

                      title        director date_added     type
0               Alias Grace             NaN 2017-11-03  TV Show
1            A Patch of Fog  Michael Lennox 2017-04-15    Movie
2                  Lunatics             NaN 2019-04-19  TV Show
3                 Uriyadi 2     Vijay Kumar 2019-08-02    Movie
4         Shrek the Musical     Jason Moore 2013-12-29    Movie
...                     ...             ...        ...      ...
5832            The Pursuit     John Papola 2019-08-07    Movie
5833       Hurricane Bianca   Matt Kugelman 2017-01-01    Movie
5834           Amar's Hands  Khaled Youssef 2019-04-26    Movie
5835  Bill Nye: Science Guy  Jason Sussberg 2018-04-25    Movie
5836           Age of Glory             NaN        NaT  TV Show

[5837 rows x 4 columns]

In [8]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   datetime64[ns]
 3   type        5837 non-null   object
dtypes: datetime64[ns](1), object(3)
memory usage: 182.5+ KB

In [13]:
netflix["type"].value_counts()

type
Movie      3939
TV Show    1898
Name: count, dtype: int64

In [23]:
netflix["type"]=netflix["type"].astype("category")

In [24]:
netflix.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5837 entries, 0 to 5836
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   title       5837 non-null   object
 1   director    3936 non-null   object
 2   date_added  5195 non-null   datetime64[ns]
 3   type        5837 non-null   category
dtypes: category(1), datetime64[ns](1), object(2)
memory usage: 142.8+ KB

In [34]:
#제목이 Limitless인 콘텐츠 찾기
title=netflix["title"]=="Limitless"
netflix[title]

          title         director date_added     type
1559  Limitless      Neil Burger 2019-05-16    Movie
2564  Limitless              NaN 2016-07-01  TV Show
4579  Limitless  Vrinda Samartha 2019-10-01    Movie

In [29]:
#Robert Rodriguez감독의 영화
direc=netflix["director"]=="Robert Rodriguez"
movie=netflix["type"]=="Movie"
netflix[direc&movie]

,title,director,date_added,type
1384,Spy Kids: All the Time in the World,Robert Rodriguez,2019-02-19,Movie
1416,Spy Kids 3: Game Over,Robert Rodriguez,2019-04-01,Movie
1460,Spy Kids 2: The Island of Lost Dreams,Robert Rodriguez,2019-03-08,Movie
2890,Sin City,Robert Rodriguez,2019-10-01,Movie
3836,Shorts,Robert Rodriguez,2019-07-01,Movie
3883,Spy Kids,Robert Rodriguez,2019-04-01,Movie

In [30]:
#2019-07-31 등록되었거나 Robert Altman가 감독인 콘텐츠
date=netflix["date_added"]=="2019-07-31"
direc=netflix["director"]=="Robert Altman"
netflix[date|direc]

                                title       director date_added     type
611                            Popeye  Robert Altman 2019-11-24    Movie
1028        The Red Sea Diving Resort    Gideon Raff 2019-07-31    Movie
1092                     Gosford Park  Robert Altman 2019-11-01    Movie
3473  Bangkok Love Stories: Innocence            NaN 2019-07-31  TV Show
5117                       Ramen Shop      Eric Khoo 2019-07-31    Movie

In [35]:
#감독이 "Orson Welles","Aditya Kripalani" 또는 "Sam Raimi"인 모든 콘텐츠 찾기
direc=["Orson Welles","Aditya Kripalani", "Sam Raimi"]
filtering=netflix["director"].isin(direc)
netflix[filtering]

                           title          director date_added   type
946                 The Stranger      Orson Welles 2018-07-19  Movie
1870                    The Gift         Sam Raimi 2019-11-20  Movie
3706                Spider-Man 3         Sam Raimi 2019-11-01  Movie
4243        Tikli and Laxmi Bomb  Aditya Kripalani 2018-08-01  Movie
4475  The Other Side of the Wind      Orson Welles 2018-11-02  Movie
5115    Tottaa Pataaka Item Maal  Aditya Kripalani 2019-06-25  Movie

In [42]:
#2019.5.1~2019.6.1 사이에 등록된 모든 콘텐츠 찾기
find=netflix["date_added"].between(
    "2019-05-01",
    "2019-06-01"
)
netflix[find].sort_values("date_added")

,title,director,date_added,type
5829,The Kindness Diaries,NaN,2019-05-01,TV Show
1153,American Experience: The Island Murder,Mark Zwonitzer,2019-05-01,Movie
1975,Sur Sapata,Mangesh Kanthale,2019-05-01,Movie
2003,Teenage Mutant Ninja Turtles,Kevin Munroe,2019-05-01,Movie
378,John & Yoko: Above Us Only Sky,Michael Epstein,2019-05-01,Movie
...,...,...,...,...
2733,Small Soldiers,Joe Dante,2019-06-01,Movie
4078,Love Is a Story,Cristina Jacob,2019-06-01,Movie
4890,Life in the Doghouse,Ron Davis,2019-06-01,Movie
3309,The Phantom of the Opera,Joel Schumacher,2019-06-01,Movie
170,Carrie,Brian De Palma,2019-06-01,Movie

In [47]:
#director가 NaN값인 행을 제거
direc_nan=netflix["director"].notnull()
netflix[direc_nan]

                                   title        director date_added   type
1                         A Patch of Fog  Michael Lennox 2017-04-15  Movie
3                              Uriyadi 2     Vijay Kumar 2019-08-02  Movie
4                      Shrek the Musical     Jason Moore 2013-12-29  Movie
5                       Schubert In Love     Lars Büchel 2018-03-01  Movie
6     We Have Always Lived in the Castle   Stacie Passon 2019-09-14  Movie
...                                  ...             ...        ...    ...
5830                         Bibi & Tina     Detlev Buck 2017-04-15  Movie
5832                         The Pursuit     John Papola 2019-08-07  Movie
5833                    Hurricane Bianca   Matt Kugelman 2017-01-01  Movie
5834                        Amar's Hands  Khaled Youssef 2019-04-26  Movie
5835               Bill Nye: Science Guy  Jason Sussberg 2018-04-25  Movie

[3936 rows x 4 columns]

In [56]:
#keep매개변수를 Flase로 설정하면 date_added열에 중복 항목이 있는 모든 행을 제거한다.
#이를 통해 콘텐츠를 단 하나만 등록한 날짜를 식별할 수 있다.
netflix.drop_duplicates(subset="date_added",keep=False)

,title,director,date_added,type
4,Shrek the Musical,Jason Moore,2013-12-29,Movie
12,Without Gorky,Cosima Spender,2017-05-31,Movie
30,Anjelah Johnson: Not Fancy,Jay Karas,2015-10-02,Movie
38,One Last Thing,Tim Rouhana,2019-08-25,Movie
70,Marvel's Iron Man & Hulk: Heroes United,Leo Riley,2014-02-16,Movie
...,...,...,...,...
5748,Menorca,John Barnard,2017-08-27,Movie
5749,Green Room,Jeremy Saulnier,2018-11-12,Movie
5788,Chris Brown: Welcome to My Life,Andrew Sandler,2017-10-07,Movie
5789,A Very Murray Christmas,Sofia Coppola,2015-12-04,Movie
5812,Little Singham in London,Prakash Satam,2019-04-22,Movie