In [1]:
import pandas as pd

In [2]:
cars=pd.read_csv("used_cars.csv")
cars.head()

  Manufacturer  Year Fuel Transmission  Price
0        Acura  2012  Gas    Automatic  10299
1       Jaguar  2011  Gas    Automatic   9500
2        Honda  2004  Gas    Automatic   3995
3    Chevrolet  2016  Gas    Automatic  41988
4          Kia  2015  Gas    Automatic  12995

In [3]:
min_wage=pd.read_csv("minimum_wage.csv")
min_wage.head()

        State  2010  2011  2012  2013  2014  2015   2016   2017
0     Alabama  0.00  0.00  0.00  0.00  0.00  0.00   0.00   0.00
1      Alaska  8.90  8.63  8.45  8.33  8.20  9.24  10.17  10.01
2     Arizona  8.33  8.18  8.34  8.38  8.36  8.50   8.40  10.22
3    Arkansas  7.18  6.96  6.82  6.72  6.61  7.92   8.35   8.68
4  California  9.19  8.91  8.72  8.60  9.52  9.51  10.43  10.22

In [4]:
#cars에서 가격의 합계를 집계하세요. 행 축에서 연료 유형별로 결과를 그룹화하세요.
cars.pivot_table(index="Fuel",values="Price",aggfunc="sum")

                Price
Fuel
Diesel      986177143
Electric     18502957
Gas       86203853926
Hybrid       44926064
Other       242096286

In [25]:
#cars에서 자동차의 개수를 aggregate하세요. index축에서 제조업체별로 결과를 그룹화하고 열 축에서 변속기 유형을 그룹화하세요. 행과 열 모두에 대한 소계를 표시하세요.
cars.pivot_table(index="Manufacturer",
                 columns="Transmission",
                 values="Price",
                 aggfunc="count",
                 fill_value=0,
                 margins=True
).head()

Transmission  Automatic  Manual  Other    All
Manufacturer
Acura              3443     141     48   3632
Alfa-Romeo           50       0     11     61
Aston-Martin         20       5      0     25
Audi               4974     375     69   5418
BMW               11641     774    627  13042

In [14]:
#cars에서 자동차의 평균 가격을 aggregate하세요. index축에 연도 및 연료 유형별로 결과를 그룹화하고 열 축에 변속기 유형을 그룹홯하세요.
report=cars.pivot_table(index=["Fuel","Year"],
                 columns="Transmission",
                 values=["Price"],
                 aggfunc="mean"
)
report

                     Price
Transmission     Automatic        Manual         Other
Fuel   Year
Diesel 2000   11326.176962  14010.164021  11075.000000
       2001   11884.000000  13969.977401  21398.857143
       2002   12324.431624  14395.405714  10817.600000
       2003   13662.669875  32914.542553   9609.100000
       2004   13480.886752  16843.594444  33633.473684
...                    ...           ...           ...
Other  2016   21058.118936  20343.521739  21528.136719
       2017   22481.452321  24401.517241  19638.598253
       2018   21990.859031  38987.222222  18573.035714
       2019   25476.572954  32501.333333  22680.709677
       2020   22210.306452           NaN   2725.925926

[102 rows x 3 columns]

In [17]:
#3번 문제의 DataFrame이 주어졌을 때 열 축에서 행 축으로 변속기 유형을 옮기세요.
report.stack()

/var/folders/g2/m_rjbg_d4fq330k9g6z2v24m0000gn/T/ipykernel_1663/2211429977.py:2: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  report.stack()

                                 Price
Fuel   Year Transmission
Diesel 2000 Automatic     11326.176962
            Manual        14010.164021
            Other         11075.000000
       2001 Automatic     11884.000000
            Manual        13969.977401
...                                ...
Other  2019 Automatic     25476.572954
            Manual        32501.333333
            Other         22680.709677
       2020 Automatic     22210.306452
            Other          2725.925926

[274 rows x 1 columns]

In [26]:
#min_wage를 wide형식에서 narrow형식으로 변환하세요. 즉 8개의 연도 열에 있는 데이터를 하나의 열로 옮기세요.
year_variable=["2010","2011","2012","2013","2014","2015","2016","2017"]
min_wage.melt(id_vars="State",
              value_vars=year_variable,
              var_name="Year",
              value_name="Wage"
)

             State  Year   Wage
0          Alabama  2010   0.00
1           Alaska  2010   8.90
2          Arizona  2010   8.33
3         Arkansas  2010   7.18
4       California  2010   9.19
..             ...   ...    ...
435       Virginia  2017   7.41
436     Washington  2017  11.24
437  West Virginia  2017   8.94
438      Wisconsin  2017   7.41
439        Wyoming  2017   5.26

[440 rows x 3 columns]