In [1]:
import pandas as pd

In [12]:
pd.read_csv("restaurant/week_1_sales.csv").head()

   Customer ID  Food ID
0          537        9
1           97        4
2          658        1
3          202        2
4          155        9

In [13]:
week1=pd.read_csv("restaurant/week_1_sales.csv")
week2=pd.read_csv("restaurant/week_2_sales.csv")

In [10]:
pd.read_csv("restaurant/customers.csv",index_col="ID").head()

   First Name Last Name  Gender  Company                     Occupation
ID
1      Joseph   Perkins    Male  Dynazzy  Community Outreach Specialist
2    Jennifer   Alvarez  Female     DabZ        Senior Quality Engineer
3       Roger     Black    Male  Tagfeed              Account Executive
4      Steven     Evans    Male     Fatz               Registered Nurse
5        Judy  Morrison  Female  Demivee                Legal Assistant

In [5]:
customers=pd.read_csv("restaurant/customers.csv",index_col="ID")

In [14]:
#2주간의 판매 데이터를 하나의 DataFrame으로 결합하세요. week1 DataFrame에 "Week 1"라는 키를 할당하고 week2 DataFrame에 "Week 2"라는 키를 할당하세요.
pd.concat(objs=[week1,week2],keys=["Week 1","Week 2"])

            Customer ID  Food ID
Week 1 0            537        9
       1             97        4
       2            658        1
       3            202        2
       4            155        9
...                 ...      ...
Week 2 245          783       10
       246          556       10
       247          547        9
       248          252        9
       249          249        6

[500 rows x 2 columns]

In [44]:
#2주 동안 매주 식당에서 식사한 고객을 찾으세요.
two_week=week1.merge(week2,how="inner",on="Customer ID").drop_duplicates(subset=["Customer ID"])
two_week.head()

   Customer ID  Food ID_x  Food ID_y
0          537          9          5
1          155          9          3
2          503          5          8
5          550          6          7
6          101          7          4

In [31]:
#2주동안 매주 식당에서 식사를 하고 같은 음식을 주문한 고객을 찾으세요.
week1.merge(week2,how="inner",on=["Customer ID","Food ID"])

   Customer ID  Food ID
0          304        3
1          540        3
2          937       10
3          233        3
4           21        4
5          922        1
6           21        4
7          578        5
8          578        5

In [47]:
#1주차에만 방문한 고객과 2주차에만 방문한 고객이 누군지 확인하세요.
week1.merge(week2,how="outer",on="Customer ID",indicator=True).head()

   Customer ID  Food ID_x  Food ID_y      _merge
0            3        2.0        NaN   left_only
1            8        NaN        6.0  right_only
2           10        2.0        NaN   left_only
3           13        NaN        2.0  right_only
4           20        1.0        NaN   left_only

In [48]:
only=week1.merge(week2,how="outer",on="Customer ID",indicator=True).head()
in_one_week=only["_merge"]=="left_only"
only[in_one_week].head()

   Customer ID  Food ID_x  Food ID_y     _merge
0            3        2.0        NaN  left_only
2           10        2.0        NaN  left_only
4           20        1.0        NaN  left_only

In [46]:
#week1 DataFrame의 각 행은 음식을 주문한 고객을 나타냅니다. 각 행에 대한 고객의 정보를 customers Dataframe에서 가져오세요.
week1.merge(customers,how="left",left_on="Customer ID",right_index=True)

,Customer ID,Food ID,First Name,Last Name,Gender,Company,Occupation
0,537,9,Cheryl,Carroll,Female,Zoombeat,Registered Nurse
1,97,4,Amanda,Watkins,Female,Ozu,Account Coordinator
2,658,1,Patrick,Webb,Male,Browsebug,Community Outreach Specialist
3,202,2,Louis,Campbell,Male,Rhynoodle,Account Representative III
4,155,9,Carolyn,Diaz,Female,Gigazoom,Database Administrator III
...,...,...,...,...,...,...,...
245,413,9,Diane,Bailey,Female,Wikibox,Technical Writer
246,926,6,Anne,Wagner,Female,Skyba,Legal Assistant
247,134,3,Diana,Hall,Female,Quinu,Financial Advisor
248,396,6,Juan,Romero,Male,Zoonder,Analyst Programmer
249,535,10,Nancy,Cox,Female,Trudeo,Research Associate