In [1]:
import pandas as pd

In [4]:
investments=pd.read_csv("investments.csv")
investments

,Name,Market,Status,State,Funding Rounds
0,#waywire,News,Acquired,NY,1
1,&TV Communications,Games,Operating,CA,2
2,-R- Ranch and Mine,Tourism,Operating,TX,2
3,004 Technologies,Software,Operating,IL,1
4,1-4 All,Software,Operating,NC,1
...,...,...,...,...,...
27794,Zynga,Technology,Operating,CA,9
27795,Zyngenia,Biotechnology,Operating,MD,1
27796,ZYOMYX,Biotechnology,Operating,MO,4
27797,Zyrra,E-Commerce,Operating,MA,4
27798,[x+1],Enterprise Software,Operating,NY,4

In [5]:
investments.nunique()

Name              27763
Market              693
Status                3
State                61
Funding Rounds       16
dtype: int64

In [8]:
investments.set_index(keys=["Status","State","Funding Rounds"])

                                              Name               Market
Status    State Funding Rounds
Acquired  NY    1                         #waywire                 News
Operating CA    2               &TV Communications                Games
          TX    2               -R- Ranch and Mine              Tourism
          IL    1                 004 Technologies             Software
          NC    1                          1-4 All             Software
...                                            ...                  ...
          CA    9                            Zynga           Technology
          MD    1                         Zyngenia        Biotechnology
          MO    4                           ZYOMYX        Biotechnology
          MA    4                            Zyrra           E-Commerce
          NY    4                            [x+1]  Enterprise Software

[27799 rows x 2 columns]

In [9]:
investments=investments.set_index(keys=["Status","State","Funding Rounds"]).sort_index()
investments

                                                             Name  \
Status    State Funding Rounds
Acquired  AB    1                                  Hallpass Media
                2                                           Poynt
          AL    1                                       EnteGreat
                1                        Onward Behavioral Health
                1                                         Proxsys
...                                                           ...
Operating WY    1                                          TecMed
                1               Urban Tax Service and Bookkeeping
                1                                        Vartopia
                1                              Wyutex Oil and Gas
                2                            McGinley Innovations

                                             Market
Status    State Funding Rounds
Acquired  AB    1                             Games
                2                            Mobile
          AL    1               Enterprise Software
                1                     Biotechnology
                1                     Biotechnology
...                                             ...
Operating WY    1                           Medical
                1                        Consulting
                1                          Software
                1                       Oil And Gas
                2                     Biotechnology

[27799 rows x 2 columns]

In [11]:
#Status가 "Closed"인 모든 행을 추출하세요
investments.loc[("Closed",)]

                                                       Name  \
State Funding Rounds
AB    1                         Cardinal Media Technologies
      1                                    Easy Bill Online
      1                                       Globel Direct
      1                                   Ph03nix New Media
      2               SQFive Intelligent Oilfield Solutions
...                                                     ...
WI    2                                        Credit Coach
      2                                             NERITES
      3                                           Alice.com
      4                                        China Wi Max
WV    1                                 Plethora Technology

                                    Market
State Funding Rounds
AB    1               Social Network Media
      1                           Tracking
      1                   Public Relations
      1                              Games
      2                           Software
...                                    ...
WI    2                           Software
      2                      Biotechnology
      3                         E-Commerce
      4                             Mobile
WV    1                           Software

[1498 rows x 2 columns]

In [15]:
#Status가 Acquired이고 Funding Rounds가 10인 모든 행 추출
investments.xs(key=("Acquired",10),level=("Status","Funding Rounds"))

                   Name       Market
State
NY     Genesis Networks  Web Hosting
TX       ACTIVE Network     Software

In [26]:
#Status가 Operating이고 Funding Rounds가 6이고 State가 NJ인 모든 행을 추출하세요
investments.xs(key=("Operating","NJ",6),level=("Status","State","Funding Rounds"))

                                              Name             Market
Status    State Funding Rounds
Operating NJ    6               Agile Therapeutics      Biotechnology
                6                         Agilence  Retail Technology
                6                Edge Therapeutics      Biotechnology
                6                          Nistica        Web Hosting

In [30]:
#Status가 Closed이고 Funding Rounds가 8인 모든 행을 추출하세요. 이때 Name열만 추출하세요.
investments.reorder_levels(order=["Status","Funding Rounds","State"]).loc[("Closed",8),("Name")]

/var/folders/g2/m_rjbg_d4fq330k9g6z2v24m0000gn/T/ipykernel_1173/4143312238.py:2: PerformanceWarning: indexing past lexsort depth may impact performance.
  investments.reorder_levels(order=["Status","Funding Rounds","State"]).loc[("Closed",8),("Name")]

State
CA              CipherMax
CA     Dilithium Networks
CA                Moblyng
CA               SolFocus
CA               Solyndra
FL    Extreme Enterprises
GA               MedShape
NC    Biolex Therapeutics
WA             Cozi Group
Name: Name, dtype: object

In [33]:
#Status나 Funding Rounds의 값과 상관없이 State가 NJ인 모든 행을 추출하세요.
investments.xs(key=("NJ"),level=("State"))

                                              Name               Market
Status    Funding Rounds
Acquired  1                                  AkaRx        Biotechnology
          1                         Aptalis Pharma        Biotechnology
          1                                 Cadent             Software
          1                        Cancer Genetics  Health And Wellness
          1                              Clacendix           E-Commerce
...                                            ...                  ...
Operating 6                                Nistica          Web Hosting
          7               Cyclacel Pharmaceuticals        Biotechnology
          7                       PTC Therapeutics          Health Care
          8                 Svelte Medical Systems          Health Care
          11                                 Vidyo            Messaging

[512 rows x 2 columns]

In [36]:
#MultiIndex level을 DataFrame에 열로 다시 통합하세요.
investments=investments.reset_index()
investments

,Status,State,Funding Rounds,Name,Market
0,Acquired,AB,1,Hallpass Media,Games
1,Acquired,AB,2,Poynt,Mobile
2,Acquired,AL,1,EnteGreat,Enterprise Software
3,Acquired,AL,1,Onward Behavioral Health,Biotechnology
4,Acquired,AL,1,Proxsys,Biotechnology
...,...,...,...,...,...
27794,Operating,WY,1,TecMed,Medical
27795,Operating,WY,1,Urban Tax Service and Bookkeeping,Consulting
27796,Operating,WY,1,Vartopia,Software
27797,Operating,WY,1,Wyutex Oil and Gas,Oil And Gas
27798,Operating,WY,2,McGinley Innovations,Biotechnology